import { useEffect } from "react";
export default function PrivacyPolicy({ onBackHome }) {

  const lastUpdated = "June 13, 2026"; // Update this when the policy text changes

  useEffect(() => {
    window.scrollTo({
    top: 0,
    left: 0,
    behavior: "instant",
    });
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground">
        <div className="max-w-4xl mx-auto px-6 py-16">

      <section className="mb-10 rounded-xl border border-border bg-card p-6">
        <div className="border-b border-border pb-6 mb-10"></div>
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground">Last updated: {lastUpdated}</p>
        <div className="mt-6 border-b border-border" />
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Introduction</h2>
        <p className="text-muted-foreground leading-relaxed">
          VoiceForge is committed to protecting the privacy of our users. This
          Privacy Policy explains how we collect, use, and disclose information
          when you use VoiceForge's web application.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Information We Collect</h2>
        <p className="text-muted-foreground leading-relaxed">
          We may collect information that you provide directly (for example,
          voice samples you choose to record) and technical information
          generated by your device or browser (such as browser type and
          settings). Whenever possible, we keep processing local to your
          browser.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">How We Use Information</h2>
        <p className="text-muted-foreground leading-relaxed">
          We use information to provide, operate, and improve VoiceForge, to
          enable features (such as voice cloning and text-to-speech), and to
          communicate with you. We do not sell personal information.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Audio & Voice Data</h2>
        <p className="text-muted-foreground leading-relaxed">
          Voice samples you record may be sent to third-party speech services
          (Hugging Face / Chatterbox Multilingual TTS) only when you explicitly choose to clone a
          voice. Where possible, VoiceForge uses local-first processing and
          stores generated profiles in your browser's storage unless you
          explicitly export or upload them.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Cookies and Analytics</h2>
        <p className="text-muted-foreground leading-relaxed">
          We use cookies and similar technologies only as necessary for basic
          functionality and to gather anonymous analytics. You can control
          many of these settings through your browser.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Third-Party Services</h2>
        <p className="text-muted-foreground leading-relaxed">
          VoiceForge may rely on third-party services to operate certain
          features (for example, hosted speech models). These services have
          their own privacy policies; we encourage you to review them.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Data Retention</h2>
        <p className="text-muted-foreground leading-relaxed">
          We retain data only as long as necessary to provide the features you
          use. Local-only profiles stored in your browser remain until you
          clear them. If you request deletion of server-side data, we will
          follow the applicable process described in our contact information.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">User Rights</h2>
        <p className="text-muted-foreground leading-relaxed">
          You may access, update, or delete data you have provided. If you
          have concerns about how your data is handled, contact us using the
          information below.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Contact Information</h2>
        <p className="text-muted-foreground leading-relaxed">
          For questions about this Privacy Policy or to request data access or
          deletion, please open an issue at our GitHub repository or email the
          maintainers via the project contact listed in the repository.
        </p>
      </section>
      <button
        onClick={() => {
         onBackHome?.();
        }}
        className="
        inline-flex items-center
        px-4 py-2
        mb-8
        rounded-lg
        border border-border
        hover:bg-accent
        transition-colors
        "
      >
        ← Back to Home
      </button>
        </div>
    </div>
  );
}
